/* generated by Svelte v3.50.1 */
import {
	SvelteComponent,
	attr,
	create_component,
	destroy_component,
	detach,
	element,
	init,
	insert,
	mount_component,
	noop,
	safe_not_equal,
	transition_in,
	transition_out
} from "svelte/internal";

import Component from "../lib/comp.wx";

function create_fragment(ctx) {
	let div;
	let component;
	let current;
	component = new Component({});

	return {
		c() {
			div = element("div");
			create_component(component.$$.fragment);
			attr(div, "class", "hive");
		},
		m(target, anchor) {
			insert(target, div, anchor);
			mount_component(component, div, null);
			current = true;
		},
		p: noop,
		i(local) {
			if (current) return;
			transition_in(component.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(component.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(div);
			destroy_component(component);
		}
	};
}

class Component_1 extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Component_1;