[package]
name = "waxc_errors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
waxc_lexer = { path = "../waxc_lexer" }
colored = "2.0.0"