/* generated by Svelte v3.50.1 */
import {
	SvelteComponent,
	append_styles,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from "svelte/internal";

function add_css(target) {
	append_styles(target, "svelte-1i735pe", "h1.svelte-1i735pe{color:#eee}p.svelte-1i735pe{color:#aaa}");
}

function create_fragment(ctx) {
	let section;

	return {
		c() {
			section = element("section");

			section.innerHTML = `<h1 class="svelte-1i735pe">Header</h1> 
  <p class="svelte-1i735pe">Paragraph</p>`;
		},
		m(target, anchor) {
			insert(target, section, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(section);
		}
	};
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {}, add_css);
	}
}

export default Component;