[package]
name = "wax_logger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wax_lexer = { path = "../wax_lexer" }
colored = "2.0.0"