[package]
name = "wax_pest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.5.0"
pest_derive = "2.5.0"

# Fancy colors in the terminal
colored = "2.0.0"