[package]
name = "wax_lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wax_logger = { path = "../wax_logger" }
peekmore = "1.0.0"